#!/bin/bash

files=(
    Bootstrap-3-
    Deepin--
    Sourc-e-Code-
    LPIC-2--
    sublime-
    sublime-
    LPIC-1-
    raspberry-
    NVIDIA--
    LPIC-1-
    IM-ARTIGOS--
    portfolio_branding_nitrux_logo_design-
    yt-
    lw-
    Linux-Dell-
    Boot-linux-5-minutos-blog-
    Pen-Drive-
    TROUBLESHOOTING-
    LPIC-1-
    RAID--
    RAID-2--
    RAID-3--
    Go-Terminal-
    Imagens-Artigos--
    LPIC-1-
    OBS-Studio-
    NVME-
    INODE--
    uefi-
    LPIC-2--
    CHAVE-PUBLICA-E-PRIVADA--
    Shutter-
    Q4OS-
    CIDR--
    1459914160viv_icon-
    Stacer-
    LPIC-2--
    Firefox-Quantum-
    CRT-
    Nylas-
    ITIL-Foundation--
    Redshift-
    Intel-Linux-
    LPIC-1-
    Cockpit-
    Dia-
    lfcs--
    WPS-
    evernote-
    CompTIA-LINUX--
    glpi-
    Google-drive-
    atalhos-teclado-
    personalização-1-
    Conky-
    VI-
    Segurança-da-informação-
    Google-Authenticator-
    NMAP-
    senha-grub-
    Medley-
    lvm-
    brackets-
    amarok-
    LVM2-
    gtop-
    kernel-
    MÉTODO-DE-AUTENTICAÇÃO-SUDO--
    manjaro-
    monit-
    STANDARD--
    STREMIO-
    NATTT-
    REDIRECIONAMENTO-DE-COMANDOS--
    appimage-
    Docky-
    DU--
    Lutris-
    wps-manjaro-
    lfce--
    Lol-
    discord-
    UMASK1-
    dota-
    TPM-
    DF--
    SSH-
    lamp-
    etc--
    man-
    ownCloud-X-release-featured-image-
    PGREP--
    Segurança-da-informação-
    NVIDIA--
    linux-foundation-
    LOAD-AVERAGE-MÉDIA-DE-CARGA--
    python-
    Firejail-
    wall--
    atom-
    e-book-
    SCREEN--
    outcert-
    ubunto-upgrade-
    virtual-host-apache--
    nipe-
    PERL-
    instrutor-udemy-
    virtual-host-SELINUX-
    glmark2-
    NVIDIS-VS-OPEN-SOURCE-
    virtual-host-https--
    aparencia-linux-
    nextcloud-
    ULIMIT--
    touchpad--
    nginx-
    nohup--
    telegram-
    ZABBIX-
    fuser--
    boot-linux-
    zabbix-grafana-
    find--
    geekbench-
    FOREMOST-
    ALIAS--
    vs-code-
    python-2-
    expand-e-unexpand--
    pendrive-g-
    endless-os-
    unboxing--
    etcher-
    bash-zsh-
    MAN-IN-THE-MIDDLE--
    pendrive-
    canon-
    linux-uefi--
    erro-linux-
    DEBUGFS-
    linux-essentials--
    ZSH-
    DUTREE-
    SWAP--
    brave-
    teamviewer-
    nvidia-video--
    WAYLAND-X11-
    Lynis-
    BASH-JM-SHELL-
    peek-
    lpi--
    franz-
    TUNED-
    vs-code--
    snipe-it-
    blog-yt-
    clear-linux-
    rsync-newbie-
    ATALHOS-
    SSD-LINUX-
    centos-
    ubunto-shutter-
    virtualbox-
    virtualbox-backup-
    exfat-no-linux-
    AAAAA-
    fz-
    slak-
    warsaw-pronto-
    APACHEREV-
    thumb-syncthing-
    thumb-iptables-
    min-browser-
    zstd-
    capa-comptia-
    capa-tema-dark-
    LPIC-1-
    10DICAS-
    Untitled-
    terminal-
    sweet-
    comptia-
    processo-de-boot-
    umask-
    FHS-
    lspci-
    lsmod-
    sudo-
    Sem-título-
    capa-wall-
    laodaverage-
    capa-raid-
    capa-raid_2-
    capa-raid-1-
    pgrep-
    inode-
    5-dicas-
    server-vs-desktop-
    dns-
    centos-
    vagrant-
    RH-
    5dicas-
    java-
    PROXY-
    irpf-
    debian-
    podcast-
    APT-
    5-variaveis-
    DAVINCI-
    eval-
    looping-
    testes-
    shebang-
    posix-
    nvidia_obs-
    to_davinci-
    MYPAINY-
    entrevista-
    ssh-
    5DICAS-
    BUGS-
    hacktoberfest-
    GITHUB-
    mint-
    SUDO-
    NVIDIA-
    MODPROBE-
    UBUNTU-
    temperatura-
    nvidia-
    lastpass-
    PARTICAO-
    FLAMESHOT-
    LPIC-
    GNOME-
    bash_performance-
    XFS-
    arq-
    NOTION-
    ruby-
    pipeline-
)

for i in ${files[@]}; do
    find . -iname "$i*" -exec rm -f {} \;
done